name: CI Test

on:
  push:
    branches: [ main ]
    paths:
      - '**.ts'
      - '**.yml'
      - 'package*.json'
  pull_request:
    branches: [ main ]
    paths:
      - '**.ts'
      - '**.yml'
      - 'package*.json'

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Build and Test
      id: build
      run: |
        npm ci
        npm run build
        npm run test

